Add gcloud_component beta to compute-ssh action
Added required gcloud_component parameter to WIF SSH action.

Otherwise you get this error:

> ERROR: gcloud crashed (NotImplementedError): SSH using federated workforce identities is not yet generally available (GA). Please use `gcloud beta compute ssh` to SSH using a third-party identity.

Signed-off-by: Jim Angel <jimangel@users.noreply.github.com>